# Generated by Django 5.1.15 on 2026-02-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bandwidth', models.FloatField()),
                ('channel', models.PositiveSmallIntegerField()),
                ('transfer_rate', models.FloatField()),
            ],
            options={
                'verbose_name': 'DRAM',
                'verbose_name_plural': 'DRAMs',
            },
        ),
    ]
