# Generated by Django 5.1.15 on 2026-02-09 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DramComponent',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.component')),
                ('capacity_gb', models.PositiveIntegerField()),
                ('speed_mhz', models.PositiveIntegerField()),
                ('ddr_type', models.CharField(max_length=10)),
                ('modules', models.PositiveIntegerField(default=1)),
                ('cas_latency', models.PositiveIntegerField(blank=True, null=True)),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'verbose_name': 'DRAM Component',
                'verbose_name_plural': 'DRAM Components',
            },
            bases=('components.component',),
        ),
    ]
