# Generated by Django 5.1.15 on 2026-02-09 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuComponent',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.component')),
                ('cores', models.PositiveIntegerField()),
                ('threads', models.PositiveIntegerField()),
                ('clock_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('boost_clock', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tdp', models.PositiveIntegerField(blank=True, null=True)),
                ('socket', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'CPU Component',
                'verbose_name_plural': 'CPU Components',
            },
            bases=('components.component',),
        ),
    ]
