# Generated by Django 5.1.15 on 2026-02-24 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedPropertySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(blank=True, help_text='Model type for the set (e.g. ResultWorkload). Null for generic sets.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extended_property_sets', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_formula', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, help_text='Model type binding for entity-level props. Null for result-level.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extended_properties', to='contenttypes.contenttype')),
                ('property_set', models.ForeignKey(blank=True, help_text='Set binding for result-level props. Null for entity-level.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.extendedpropertyset')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedPropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.JSONField(help_text='Formula string (when is_formula=True) or literal value')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_property_values', to='contenttypes.contenttype')),
                ('extended_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='properties.extendedproperty')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_text', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('read_only', models.BooleanField(default=False)),
                ('is_extended', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_numeric', models.BooleanField(default=False)),
                ('sub_type', models.CharField(blank=True, default='', help_text='percent, byte, etc.', max_length=50)),
                ('decimal_place', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('content_type', models.ForeignKey(help_text='Which model type this config belongs to (Nand, Cpu, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='property_configs', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['content_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyConfigSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(help_text='Which model type this set is for (Nand, Cpu, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='config_sets', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyConfigSetMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='Display order of this config within the set')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='properties.propertyconfig')),
                ('config_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='properties.propertyconfigset')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='propertyconfigset',
            name='configs',
            field=models.ManyToManyField(related_name='config_sets', through='properties.PropertyConfigSetMembership', to='properties.propertyconfig'),
        ),
        migrations.AddConstraint(
            model_name='extendedproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('content_type__isnull', False)), fields=('content_type', 'name'), name='unique_extended_prop_per_model_type'),
        ),
        migrations.AddConstraint(
            model_name='extendedproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('property_set__isnull', False)), fields=('property_set', 'name'), name='unique_extended_prop_per_set'),
        ),
        migrations.AddConstraint(
            model_name='extendedproperty',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content_type__isnull', False), ('property_set__isnull', True)), models.Q(('content_type__isnull', True), ('property_set__isnull', False)), _connector='OR'), name='extended_prop_single_binding'),
        ),
        migrations.AddIndex(
            model_name='extendedpropertyvalue',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_ext_prop_value_instance'),
        ),
        migrations.AddConstraint(
            model_name='extendedpropertyvalue',
            constraint=models.UniqueConstraint(fields=('extended_property', 'content_type', 'object_id'), name='unique_value_per_prop_per_instance'),
        ),
        migrations.AddConstraint(
            model_name='propertyconfig',
            constraint=models.UniqueConstraint(fields=('content_type', 'name'), name='unique_config_per_model_type'),
        ),
        migrations.AddConstraint(
            model_name='propertyconfigsetmembership',
            constraint=models.UniqueConstraint(fields=('config_set', 'config'), name='unique_config_in_set'),
        ),
        migrations.AddConstraint(
            model_name='propertyconfigsetmembership',
            constraint=models.UniqueConstraint(fields=('config_set', 'index'), name='unique_index_in_set'),
        ),
        migrations.AddConstraint(
            model_name='propertyconfigset',
            constraint=models.UniqueConstraint(fields=('content_type', 'name'), name='unique_config_set_per_model_type'),
        ),
    ]
