# Generated by Django 5.1.15 on 2026-02-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedproperty',
            name='default_value',
            field=models.JSONField(blank=True, default=None, help_text='Fallback value for instances with no per-instance value record', null=True),
        ),
    ]
